export interface ProductInfo {
    link: string,
    currency: string,
    available: string,
    name: string,
    manufacturer: string,
    skus: string[],
    prices: number[],
    description: string,
    descriptionHtml: string,
    unitName: string,
    discount: string,
    combinations: any[],
    photos: string[],
}
